### PR TITLE
Fix #13 - Support Pyramid 2.0 / Python 3.6+ only

### LINKED ISSUE #13: Support Pyramid 2.0
`pyramid.compat` has been removed, causing this import to fail:

https://github.com/usingnamespace/pyramid_authsanity/blob/8ecbe63dba8f6db57c9e216fecde303e0d942461/src/pyramid_authsanity/sources.py#L1

### PR DESCRIPTION
**Pull request by stevepiercy**
This is a WIP.

I don't know where to begin to fix the test errors, like these:

```
FAILED tests/test_authpolicy.py::TestAuthServicePolicyIntegration::test_find_services - AttributeError: 'DummyRequest' object has no attribute 'services'
...
FAILED tests/test_includeme.py::TestAuthServicePolicyIntegration::test_include_me - LookupError: could not find registered service
FAILED tests/test_sources.py::TestHeaderAuthSource::test_headers_remember - TypeError: _native() takes from 1 to 3 positional arguments but 4 were given
```

That last error about `_native` is especially annoying, and I've tried a half-dozen permutations, none of which worked.

See #13

### CODE REVIEW

**Comment by invisibleroads** [comment]
@bertjwregeer

**Comment by digitalresistor** [comment]
@invisibleroads tagging me is not necessary, as this is my project, I already got notified on it. Thanks! I will get to it when I have a chance.

**Comment by invisibleroads** [comment]
Awesome that Pyramid 2 is out

**Comment by stevepiercy** [comment]
@bertjwregeer I just pushed a commit with GitHub Actions following Pyramid 2.0's example, but it will not run until you enable it in the repo settings.

I'm also available to do some pair programming with anyone who wants to contribute to this PR. Please ping me and I'll grant write access to my fork.

**Comment by digitalresistor** [comment]
Actions are turned on in settings. I think the issue is that this was a PR made outside of the repo and it is net-new.

**Comment by stevepiercy** [comment]
If you grant me write access while protecting `master` so I don't do anything stupid, I could try pushing this branch to your repo and open a new PR to see if that starts GHA. [That worked with Deform](https://github.com/Pylons/deform/pull/492/files).

**Pull request merged**
